### ISSUE TITLE
Replace yarn with npm

### ISSUE THREAD

**Issue by kvikshaug** [DD-DeCaF/metabolica-ui#2]
For consistency with other FE repos we should standardize on either npm or yarn

**Comment by siddC** [comment]
As in we should exclusively use `npm` or exclusively use `yarn`?

**Comment by kvikshaug** [comment]
Exactly, if there are no good arguments that different tools are preferable in different situations I think it's a good idea to consistently use one or the other.

**Comment by matyasfodor** [comment]
So what are the pros and cons? There was a big buzz around yarn ~1 year ago, but I'm no longer sure if one tool is better than the other. I think the npm team also accommodated the fanciest yarn features. Personally, I use npm, but I'm open to switch to yarn.

**Comment by kvikshaug** [comment]
I have the same impression, and so I would lean in favor of `npm` based only on the fact that it's closer to the Node core ecosystem and not externally developed.
